"use client";

import * as React from "react";
import { Briefcase, FileText, Loader2, Sparkles, Upload } from "lucide-react";
import { toast } from "sonner";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { api } from "@/lib/api";
import type { LangCode } from "@/types";
import { useLanguageStore } from "@/store/language";

interface Business {
  id: string;
  name: string;
  industry?: string | null;
  description?: string | null;
  country?: string | null;
  city?: string | null;
  goals: string[];
  challenges: string[];
}

interface AnalysisResponse {
  report_id: string;
  title: string;
  summary: string;
  content: Record<string, string>;
  created_at: string;
}

export default function BusinessPage() {
  const locale = useLanguageStore((s) => s.locale);
  const [businesses, setBusinesses] = React.useState<Business[]>([]);
  const [active, setActive] = React.useState<Business | null>(null);
  const [analysis, setAnalysis] = React.useState<AnalysisResponse | null>(null);
  const [creating, setCreating] = React.useState(false);
  const [analyzing, setAnalyzing] = React.useState(false);

  React.useEffect(() => {
    api.get<Business[]>("/business").then((b) => {
      setBusinesses(b);
      setActive(b[0] ?? null);
    });
  }, []);

  async function createBusiness(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setCreating(true);
    const fd = new FormData(e.currentTarget);
    try {
      const created = await api.post<Business>("/business", {
        name: String(fd.get("name")),
        industry: String(fd.get("industry") || ""),
        description: String(fd.get("description") || ""),
        country: String(fd.get("country") || ""),
        city: String(fd.get("city") || ""),
        goals: String(fd.get("goals") || "").split(",").map((s) => s.trim()).filter(Boolean),
        challenges: String(fd.get("challenges") || "").split(",").map((s) => s.trim()).filter(Boolean),
      });
      setBusinesses((b) => [created, ...b]);
      setActive(created);
      (e.target as HTMLFormElement).reset();
      toast.success("Business profile created.");
    } catch {
      toast.error("Could not create business.");
    } finally {
      setCreating(false);
    }
  }

  async function uploadDoc(file: File) {
    if (!active) return;
    toast.loading("Indexing document into your knowledge base…", { id: "rag" });
    try {
      await api.upload(`/business/${active.id}/documents`, file);
      toast.success("Document indexed.", { id: "rag" });
    } catch {
      toast.error("Upload failed.", { id: "rag" });
    }
  }

  async function runAnalysis() {
    if (!active) return;
    setAnalyzing(true);
    setAnalysis(null);
    try {
      const out = await api.post<AnalysisResponse>("/business/analyze", {
        business_id: active.id,
        language: locale as LangCode,
        report_type: "business_analysis",
      });
      setAnalysis(out);
      toast.success("Analysis complete.");
    } catch {
      toast.error("Analysis failed.");
    } finally {
      setAnalyzing(false);
    }
  }

  return (
    <div className="space-y-8 max-w-6xl mx-auto">
      <div>
        <h1 className="font-display text-3xl font-bold tracking-tight">Business AI Consulting</h1>
        <p className="text-muted-foreground mt-1">
          Describe your business, upload your docs, and get a full SWOT, automation roadmap and marketing plan
          generated by our LangGraph multi-agent workflow.
        </p>
      </div>

      <Tabs defaultValue="profile" className="space-y-6">
        <TabsList>
          <TabsTrigger value="profile">Profile</TabsTrigger>
          <TabsTrigger value="documents">Documents</TabsTrigger>
          <TabsTrigger value="report">AI Report</TabsTrigger>
        </TabsList>

        <TabsContent value="profile" className="space-y-6">
          <Card>
            <CardHeader>
              <CardTitle>Create / select a business</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              {businesses.length > 0 && (
                <div className="flex flex-wrap gap-2">
                  {businesses.map((b) => (
                    <Button
                      key={b.id}
                      variant={active?.id === b.id ? "gradient" : "outline"}
                      size="sm"
                      onClick={() => setActive(b)}
                      className="gap-2"
                    >
                      <Briefcase className="h-3.5 w-3.5" /> {b.name}
                    </Button>
                  ))}
                </div>
              )}

              <form onSubmit={createBusiness} className="grid gap-4 sm:grid-cols-2">
                <div className="space-y-2 sm:col-span-2">
                  <Label htmlFor="name">Business name</Label>
                  <Input id="name" name="name" required placeholder="Adama Coffee Co." />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="industry">Industry</Label>
                  <Input id="industry" name="industry" placeholder="Specialty coffee retail" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="country">Country</Label>
                  <Input id="country" name="country" placeholder="Ethiopia" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="city">City</Label>
                  <Input id="city" name="city" placeholder="Adama" />
                </div>
                <div className="space-y-2 sm:col-span-2">
                  <Label htmlFor="description">Short description</Label>
                  <Textarea
                    id="description"
                    name="description"
                    rows={3}
                    placeholder="A boutique coffee shop and online roastery serving 200+ daily customers…"
                  />
                </div>
                <div className="space-y-2 sm:col-span-2">
                  <Label htmlFor="goals">Top 3 goals (comma-separated)</Label>
                  <Input id="goals" name="goals" placeholder="grow online orders, automate WhatsApp, hire 2 baristas" />
                </div>
                <div className="space-y-2 sm:col-span-2">
                  <Label htmlFor="challenges">Top challenges (comma-separated)</Label>
                  <Input id="challenges" name="challenges" placeholder="slow customer support, no clear marketing plan" />
                </div>
                <div className="sm:col-span-2">
                  <Button type="submit" variant="gradient" disabled={creating}>
                    {creating ? <Loader2 className="h-4 w-4 animate-spin" /> : "Save business"}
                  </Button>
                </div>
              </form>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="documents">
          <Card>
            <CardHeader>
              <CardTitle>Knowledge base</CardTitle>
            </CardHeader>
            <CardContent>
              <label
                htmlFor="upload"
                className="flex flex-col items-center justify-center gap-2 rounded-xl border border-dashed border-border bg-muted/30 px-6 py-14 cursor-pointer hover:bg-muted/50 transition"
              >
                <Upload className="h-8 w-8 text-muted-foreground" />
                <p className="text-sm font-medium">Click to upload PDF, DOCX, TXT or CSV</p>
                <p className="text-xs text-muted-foreground">
                  Documents are parsed and indexed into your private vector knowledge base for RAG.
                </p>
                <input
                  id="upload"
                  type="file"
                  className="sr-only"
                  accept=".pdf,.docx,.doc,.txt,.csv"
                  onChange={(e) => {
                    const f = e.target.files?.[0];
                    if (f) uploadDoc(f);
                  }}
                  disabled={!active}
                />
              </label>
              {!active && (
                <p className="mt-3 text-xs text-warning">Create a business profile first.</p>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="report" className="space-y-4">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0">
              <CardTitle>AI Business Report</CardTitle>
              <Button onClick={runAnalysis} variant="gradient" disabled={!active || analyzing}>
                {analyzing ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" /> Generating…
                  </>
                ) : (
                  <>
                    <Sparkles className="h-4 w-4" /> Generate report
                  </>
                )}
              </Button>
            </CardHeader>
            <CardContent>
              {analyzing && (
                <p className="text-sm text-muted-foreground">
                  Diagnose → SWOT → automation roadmap → marketing plan → synthesis. This usually
                  takes 30-60 seconds.
                </p>
              )}
              {analysis && (
                <div className="space-y-6">
                  <div>
                    <Badge variant="gradient">Report #{analysis.report_id.slice(0, 8)}</Badge>
                    <h2 className="font-display text-2xl font-semibold mt-3">{analysis.title}</h2>
                    <p className="text-sm text-muted-foreground mt-1">{analysis.summary}</p>
                  </div>
                  {Object.entries(analysis.content).map(([section, body]) => (
                    <section key={section}>
                      <h3 className="font-display text-lg font-semibold capitalize mt-2 flex items-center gap-2">
                        <FileText className="h-4 w-4 text-primary" />
                        {section.replaceAll("_", " ")}
                      </h3>
                      <div className="mt-2 markdown-body text-sm">
                        <pre className="whitespace-pre-wrap font-sans">{body}</pre>
                      </div>
                    </section>
                  ))}
                </div>
              )}
              {!analyzing && !analysis && (
                <p className="text-sm text-muted-foreground">
                  Click "Generate report" to run the full multi-agent workflow on your business profile.
                </p>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
